services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "8080:443"
    depends_on:
      - wordpress
    networks:
      - docker-network
    volumes:
      - wordpress_files:/var/www/html
  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    volumes:
      - wordpress_files:/var/www/html
    environment:
      WORDPRESS_DB_NAME: ${DATABASE_NAME}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_USER_PASSWORD: ${MARIADB_USER_PASSWORD}
      WORDPRESS_URL: ${WORDPRESS_URL}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
    expose:
      - 9000
    depends_on:
      - mariadb
    networks:
      - docker-network
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_USER_PASSWORD: ${MARIADB_USER_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    volumes:
      - wordpress_data:/var/lib/mysql
    expose:
      - 3306
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge

volumes:
  wordpress_files:
  wordpress_data: