services:
  nginx:
    build: requirements/nginx/.
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
      - "8081:8081"
    depends_on:
      - wordpress
    networks:
      - docker-network
    volumes:
      - wordpress_files:/var/www/html
    restart: always
  wordpress:
    build: requirements/wordpress/.
    image: wordpress
    container_name: wordpress
    volumes:
      - wordpress_files:/var/www/html
    environment:
      WORDPRESS_DB_NAME: ${DATABASE_NAME}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: /run/secrets/credentials
      WORDPRESS_USER_PASSWORD: /run/secrets/db_password
      WORDPRESS_URL: ${WORDPRESS_URL}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_ADMIN_USER: /run/secrets/wp_admin_user
      WORDPRESS_ADMIN_PASSWORD: /run/secrets/wp_admin_password
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_USER_EMAIL: ${WORDPRESS_USER_EMAIL}
    expose:
      - 9000
    depends_on:
      - mariadb
    networks:
      - docker-network
    restart: always
    secrets:
      - wp_admin_password
      - wp_admin_user
      - credentials
      - db_password
  mariadb:
    build: requirements/mariadb/.
    image: mariadb
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: /run/secrets/db_root_password
      MARIADB_USER: /run/secrets/credentials
      MARIADB_USER_PASSWORD: /run/secrets/db_password
      DATABASE_NAME: ${DATABASE_NAME}
    volumes:
      - wordpress_data:/var/lib/mysql
    expose:
      - 3306
    networks:
      - docker-network
    restart: always
    secrets:
      - db_root_password
      - credentials
      - db_password
  redis:
    build: requirements/bonus/redis/.
    image: redis
    container_name: redis
    volumes:
      - redis_data:/data
    expose:
      - 6379
    networks:
      - docker-network
    restart: always
  ftp:
    build: requirements/bonus/ftp/.
    image: ftp
    container_name: ftp
    environment: 
      FTP_USER: /run/secrets/ftp_user
      FTP_PASS: /run/secrets/ftp_password
    volumes:
      - wordpress_files:/var/www/wp
    ports:
      - "21000:21"
      - "21001:21001"
    networks:
      - docker-network
    restart: always
    depends_on:
      - wordpress
    secrets:
      - ftp_user
      - ftp_password
  adminer:
    build: requirements/bonus/adminer/.
    image: adminer
    container_name: adminer
    expose:
      - 8081
    networks:
      - docker-network
    restart: always
  web:
    build: requirements/bonus/web/.
    image: web
    container_name: web
    ports:
      - "8000:8000"
    networks:
      - docker-network
    restart: always
  portainer:
    build: requirements/bonus/portainer/.
    image: portainer
    container_name: portainer
    ports:
      - "9443:9443"
    networks:
      - docker-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always

networks:
  docker-network:
    driver: bridge

volumes:
  wordpress_data:
    driver: local
    driver_opts:
        type: none
        device: /home/oait-laa/data/wordpress_data
        o: bind
  wordpress_files:
    driver: local
    driver_opts:
        type: none
        device: /home/oait-laa/data/wordpress_files
        o: bind
  redis_data:
  portainer_data:

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_admin_user:
    file: ../secrets/wp_admin_user.txt
  ftp_user:
    file: ../secrets/ftp_user.txt
  ftp_password:
    file: ../secrets/ftp_password.txt
