version: "3.8"
services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "8443:443"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - wordpress
  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    volumes:
      - ./www:/var/www/html
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
# networks:
#   net: